### PR TITLE
Created a PDF for better user experience and portability.

### PR DESCRIPTION
**Pull request by dushy98**
The PDF is more user-friendly for online Usage on github as images were not responsive to different screen resolution.

cloud-computing

### CODE REVIEW

**Comment by dushy98** [comment]
added pdfs

**Review by yash-278 — APPROVED** [review]
Looks Great

**Comment by cdrhim** [comment]
The file naming could be improved with consistency:
1. Unifying numbering with the `#1` format
2. Omitting the upper snake case (this type of naming is not conventional)
3. Deleting any numbers that follow at the end of the title

**Comment by cdrhim** [comment]
Also, the PDFs have been made up to #10. I'll help add PDFs from #11 and to the end.

**Review by cdrhim — CHANGES_REQUESTED** [review]
The file naming could be improved with consistency:
1. Unifying numbering with the `#1` format
2. Omitting the upper snake case (this type of naming is not conventional)
3. Deleting any numbers that follow at the end of the title

**Comment by dushy98** [comment]
> The file naming could be improved with consistency:
> 
> 1. Unifying numbering with the `#1` format
> 2. Omitting the upper snake case (this type of naming is not conventional)
> 3. Deleting any numbers that follow at the end of the title

**Comment by dushy98** [comment]
> The file naming could be improved with consistency:
> 
> 1. Unifying numbering with the `#1` format
> 2. Omitting the upper snake case (this type of naming is not conventional)
> 3. Deleting any numbers that follow at the end of the title

Above changes Implemented

**Comment by dushy98** [comment]
All PDFs for better User Experience

**Comment by cdrhim** [comment]
@dushy98 Thanks for the changes!

**Comment by mainakbws** [comment]
Very good work, thank you!

**Pull request merged**
